# Generated by Django 4.0.4 on 2024-05-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('emision', models.DateField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank='', default='../../static/core/img/defaultuser.png', upload_to='foto_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id_tipo_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank='', default='../../static/core/img/defaultuser.png', upload_to='foto_perfil')),
                ('id_tipo_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Comprado',
            fields=[
                ('id_producto_comprado', models.AutoField(primary_key=True, serialize=False)),
                ('id_serie', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('valor_final', models.IntegerField()),
                ('num_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(blank='', default='../../static/core/img/defaultuser.png', upload_to='foto_producto')),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.producto')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.usuario'),
        ),
    ]
