# Generated by Django 4.0.4 on 2024-05-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_usuario',
            old_name='nombre_Tipo',
            new_name='descripcion',
        ),
    ]
